### ISSUE TITLE
Replace the + (and -?) buttons in the Plugin Manager with something easier to discover

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#102]
I overlooked those initially and have noticed several times that users just do not notice those those buttons and definitely do not understand from just looking at the dialog what those buttons would do. There is a tooltip, but for that to get noticed one has to first move the cursor and wait for the tooltip to appear.
I think the functionality of these buttons is extremely important and maybe we should have big buttons with text telling us loudly what they are doing ("Register New Plugin", "Unregister Selected"). This would mean to sacrifice the equivalent of one row in the plugin table, but I think it would be worth it.

Also:  what does the "a" in the first column mean? The icon for the directory plugin is also not very intuitive (there are better "directory" icons around, I think). A tooltip to explain things may be helpful

**Comment by greenwoodma** [comment]
I'm sceptical that changing those buttons would make much difference. After all I think they've been pretty much the same since GATE v2 and we've never had a real problem with people not knowing how they work. Plus I believe it's well documented how that all works.

I agree about the "a" icon though, and that's my fault. I was originally looking for something squarish to distinguish maven plugins from directory plugins. The directory icon is the one we use throughout the UI so I'm loath to change that (unless we want to change it everywhere) but I'm open to suggestions for an alternative to the "a". Ideally it should be something that relates to maven so that in the future if we support other sources we can have appropriate icons.

**Comment by johann-petrak** [comment]
As I said, I had several situations where users needed to get those buttons and what they do pointed out to them -- they are very easy to miss and it is easy to not even notice that the plugin list can get extended by additional plugins (both maven and legacy) and plugin versions. 
Of course we can decide that we do not mind that users do not discover functionality that may be important to them, but I think it is pretty probable that somewhere between some and a lot of users miss those buttons.
