### ISSUE TITLE
PluginManager: odd sorting after adding plugin with "+"

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#124]
When I add a plugin using the "+" button and the plugin is one that is already in the list, but a different version, I would expect the added plugin to show up right next to the one in the list. Instead it appears in a very different location. 

For example, "Format: Bdoc (1.5-SNAPSHOT)" is in the current list for GATE 9.0-SNAPSHOT. When I add version "1.1-SNAPSHOT", the added line shows up 10 lines below the exising line (see screenshot). 
![pluginman](https://user-images.githubusercontent.com/619106/89630215-53781600-d89f-11ea-9965-99d4bb7a96f8.png)

Clicking the "Plugin Name" header of the table twice to re-sort will place it where it belongs: right before the existing line. 

This can be confusing when somebody adds a plugin and then it is shown at a position that is outside the visible part of the table.

**Comment by greenwoodma** [comment]
Yes, this is one of those odd unfortunate timing things. It turns out that when the plugin is first added to the model behind the table it doesn't yet have all it's metadata so it uses the artifact name, which in this case is "gateplugin-Format_Bdoc", for it's position in the table. When the metadata is fully populated it then picks up the proper name, but for some reason the table doesn't automatically resort itself.
