### ISSUE TITLE
All folders in the ResourceReference chooser are shown disabled

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gate-core#32]
Turns out the check for a trailing slash as part of the code for disabling icons when showing plugin resources doesn't work. At least on Ubuntu running under Java 9 none of the folder names end in a trailing slash so all folders are shown disabled which is very confusing.

**Comment by ianroberts** [comment]
Given the tree nodes are created by a traverse of the zip FS, we know up front which ones are supposed to be directories and which are supposed to be files, so we now store this in an explicit boolean flag on the node and have the renderer use that rather than relying on the path ending with a slash. @greenwoodma please verify this on your version of Java and close if it's fixed.

**Comment by greenwoodma** [comment]
yes, that fixed it thanks @ianroberts
