### ISSUE TITLE
Remove default -Xmx1G limitation

### ISSUE THREAD

**Issue by donpellegrino** [GateNLP/gate-core#56]
A default GATE Developer installation limits the maximum heap size to 1 gigabyte. This behavior is documented in https://gate.ac.uk/sale/tao/splitch2.html#x5-260002.4. I was unable to find any justification for this limitation. Removing the "-Xmx1G" line from gate.l4j.ini allows the JVM to use its default settings.

**Comment by ianroberts** [comment]
This likely dates back a number of years to the time when the jvm default used to be considerably smaller (tens of MB). I believe the default these days would be a quarter of the physical memory size, so it should be safe to remove the `-Xmx` without adverse effects.

**Comment by greenwoodma** [comment]
Having looked into this (I hate the way Oracle structures it's documentation) I'm not sure what the actual default is in all cases.

The description of the defaults for client and server VMs is here: https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html#default_heap_size

And the table which shows which type of VM is used is here: https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/ergonomics.html#sthref5

Reading through this (and taking into account the examples) while running under linux means you will most likely get the server VM on Windows it looks as if you only ever get the client VM,

This means that on Linux chances are the default maximum is 1/4 of your physical RAM (my laptop has 16GB and I get 4GB as the default) which you can check using the command `java -XX:+PrintFlagsFinal -version | grep HeapSize` which for me shows 4175429632 bytes.

Under Windows though and the client VM my understanding is that you get _"one fourth of the physical memory up to a physical memory size of 1 gigabyte"_. My reading of this would be that the maximum heap value would be 1GB, but the example states that _"if your computer has 128 MB of physical memory, then the maximum heap size is 64 MB, and greater than or equal to 1 GB of physical memory results in a maximum heap size of 256 MB."_ That sounds to me that regardless of the amount of RAM you have, if running under windows the default max heap will always be 256MB. If that's correct then we need to provide a default in `gate.l4j.ini` otherwise Windows users are going to struggle to do anything useful.

The question is, what would be a useful default to set? If I remember correctly (certainly under 32 bit versions of Windows) specifying too large a max heap causes the JVM to fail to start, which would be bad under Windows with people using the exe as they wouldn't see the error message.

**Comment by ianroberts** [comment]
Conversely how many people are still using 32-bit windows or 32-bit java on 64-bit windows these days, even laptops people bring to training courses seem to be x86_64 now. 32 bit the maximum `-Xmx` is around 1.5g (so the total address space including non-heap stays below 2GB).

**Comment by greenwoodma** [comment]
Good point. I think I misread the table and so didn't spot that 64 bit JVM on Windows would most likely be server style and hence the larger default. Let's remove the setting and see if anyone complains.

**Comment by ianroberts** [comment]
A possible compromise might be to put a bigger Xmx in the l4j.ini by default but then have an alternative version with a 32-bit compatible value and a conditional step in the installer that picks the right one based on the target architecture. You’d still have to manually edit if you used the zip distro on Win32 but hopefully the majority of people that it affects would be using the installer anyway.

Does the current launcher still work on 32-bit at all?

**Comment by greenwoodma** [comment]
I'd suggest we just ignore 32 bit issues. While you can still download a 32 bit Windows version of Java 8, there is only a 64 bit version of Java 10 so we won't be ale to support 32 bit Windows for much longer even if we wanted to.

**Comment by greenwoodma** [comment]
one outstanding issue is should we increase the minimum size above 200m? On my machine it defaults to 262144000 bytes if unset (which is I guess 264MB)
